[package]
name = "fitness-tracker-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
tokio = { version = "1.46.1", features = ["full"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"], optional = true }
testcontainers = { version = "0.24.0", optional = true }
testcontainers-modules = { version = "0.12.1", features = ["postgres"], optional = true }

[dev-dependencies]
serde_json = "1.0.140"
chrono = "0.4.41"
testcontainers = "0.24.0"
testcontainers-modules = { version = "0.12.1", features = ["postgres"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }

[features]
testing = ["sqlx", "testcontainers", "testcontainers-modules"]

[build-dependencies]
chrono = "0.4.41"
